baseUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
loginUsername=Admin
loginPassword=admin123
employeeName=Naruto Uzumaki
newUserPassword=Test@12345
expectedDashboardText=Dashboard
userRole=ESS
status=Enabled